---
- name: Scheduling a Cron job
  hosts: all

  tasks:
  - name: Cron job
    cron:
     minute: "5"
     hour: "12"
     month: "10"
     day: "22"
     weekday: "*"
     user: osboxes
     job: "/home/osboxes/time.sh"